LBPlayer.Lang = {
	Play: "play",
	Pause: "pause",
	Stop: "stop",
	Volume: "set volume",
	Mute: "mute",
	UnMute: "unmute",
	Fullscreen: "set to in-browser fullscreen view",
	Smallscreen: "set to minimal view",
	PlaybackRate_title: "playback rate",
	PlaybackRate_inner: "1x",
	PlaybackRate_to: "set playback rate to: ",
	PlaybackRate_2: "2x",
	PlaybackRate_1: "1x",
	PlaybackRate_05: unescape("%BD")+"x",
	PlaybackRate_025: unescape("%BC")+"x",
	Subtitle_title: "change subtitle",
	Subtitle_inner: "CC",
	Subtitle_set: "on/off",
	Subtitle_onoff: "set subtitle on/off",
	Subtitle_to: "change subtitle language to: ",
	EmbedInfo: "&lt;<span class=\"bold\">embed</span>&gt;",
	EmbedInfoTitle: "embedding information for video",
	EmbedVideo: "copy <span class=\"bold\">embed-code</span> of video",
	EmbedVideoTitle: "copy embed-code of video",
	EmbedURL: "copy <span class=\"bold\">backlink url</span> of page",
	EmbedURLTitle: "copy backling url of page",
	EmbedCodeTxt: "Copy (CTRL+C) the code above and integrate it to your page.",
	EmbedBtn: "close",
}